### PR TITLE
Solid Lines + Draw on screen

### PR DESCRIPTION
**Pull request by maxxfrazer**
- Added a pod, SCNLine, to draw the lines rather than adding spheres
- Replaced some of the maths ready to be able to draw anywhere on screen
- Have currently pushed the drawing to 0.5m from the camera, see if you like it or not; can revert

### CODE REVIEW

**Comment by maxxfrazer** [comment]
Here's how the current state looks:

BB412057-A8C0-42D7-9727-3E364B8AD899

**Comment by maxxfrazer** [comment]
@ShawnMa16 could you let me know if you're interested in these features? Resolving conflicts is tough when pods are involved 😅

**Comment by kimberlytangha** [comment]
What a great modification 😃👏🏼

**Comment by ShawnMa16** [comment]
Love this, I just created a 'drawingWithLine' branch, could you please push your version to this?
Thanks!

**Pull request closed without merging**
